/**
 * Do not edit directly, this file was auto-generated.
 */

export const ColorFuncOne010 = "#e5f7f4";
export const ColorFuncOne020 = "#98ddd2";
export const ColorFuncOne030 = "#53c6b4";
export const ColorFuncOne040 = "#30bba5";
export const ColorFuncOne050 = "#2cac97";
export const ColorFuncOne060 = "#289c8a";
export const ColorFuncThree010 = "#fef8ea";
export const ColorFuncThree020 = "#ffedaf";
export const ColorFuncThree030 = "#ffde71";
export const ColorFuncThree040 = "#facb4d";
export const ColorFuncThree050 = "#f7bd2b";
export const ColorFuncThree060 = "#efae09";
export const ColorFuncTwo010 = "#ffe9ec"; // 警示 / 特殊 functional 的 foundation 用色
export const ColorFuncTwo020 = "#ff9eaa"; // 警示 / 特殊 functional 的 icon 用色
export const ColorFuncTwo030 = "#f86173";
export const ColorFuncTwo040 = "#e63349";
export const ColorFuncTwo050 = "#d7213e";
export const ColorFuncTwo060 = "#c41428";
export const ColorGray090 = "#66666a";
export const ColorNeutral100 = "#515156"; // 商品卡的商品特點標籤
export const ColorNeutral110 = "#45454a";
export const ColorNeutral120 = "#39393e"; // 介面文字深色用色
export const ColorNeutral130 = "#2c2c32"; // 用於 title / icon / 文字按鈕入口
export const ColorNeutral140 = "#202026"; // 介面文字強調用色
export const ColorNeutral000 = "#ffffff"; // 背景的 default 用色；default on primary 文字用色
export const ColorNeutral010 = "#f7f7f8"; // 用於背景色淺色
export const ColorNeutral020 = "#eeeeef"; // 用於背景色
export const ColorNeutral030 = "#e5e5e5"; // 用於背景深色；divider 用色；用於元件的外框淺色
export const ColorNeutral040 = "#d3d3d5"; // divider 深色用色
export const ColorNeutral050 = "#bfbfc1"; // 用於元件的外框中性色
export const ColorNeutral060 = "#a8a8ab"; // 介面文字深色淺色
export const ColorNeutral070 = "#929295"; // 介面文字深色中性色
export const ColorNeutral080 = "#7c7c80"; // 用於元件的外框深色
export const ColorNeutral090 = "#66666a"; // 介面文字深色用色；icon 用色
export const ColorPrimary010 = "#eff7fd"; // Primary Background Color Weak：default 元件強調時的背景色；未讀訊息的背景色
export const ColorPrimary020 = "#d2dde4"; // page foundation 的背景色，較灰階以表現消極感，用於失敗的空白頁面
export const ColorPrimary030 = "#2e90b7"; // text link / text button 或元件上需強調時的用色；商品卡 badge 背景色；Pagination selected 用色
export const ColorPrimary040 = "#10567b"; // 交互時 hover 的交互色；primary button hover 交互色
export const ColorPrimary050 = "#064162"; // 交互時 hover 的交互色；primary button hover 交互色
export const ColorPrimary060 = "#003354"; // call to action focus 用色，例如 button-primary active / bottom bar active；商品卡售價用色
export const ColorSecondary010 = "#fff8f7"; // Weak discount color，用於優惠元件的背景色，例如 campaign banner、trending badge
export const ColorSecondary020 = "#f5b3ae"; // 用於元件上的 text color，例如 coach mark 的 title
export const ColorSecondary030 = "#ee847d"; // 商品卡上的 badge 背景色；Pinkoi Logo 次要品牌色
export const ColorSecondary040 = "#f16c5d"; // purchase button 的 default 背景色；通知提示、狀態、switch、首頁 tab；介面上的購買行為文字訊息
export const ColorSecondary050 = "#e56051"; // 購買行為按鈕交互時 hover 的交互色
export const ColorSecondary060 = "#da5648"; // 購買行為交互色，例如 purchase / add to cart button active；filter & sort active；check box selected
